["libtiff-4.0.9"]
cve = [ "CVE-2017-18013", "CVE-2017-17095", "CVE-2018-7456", "CVE-2018-8905", "CVE-2018-5784", "CVE-2017-17942" ]
issue_url ="https://fb.flyingcircus.io/f/cases/101123/"

["rsync-3.1.3"]
cve = [ "CVE-2017-16548" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101092/"

["protobuf 2.6.1"]
cve = [ "CVE-2015-5237" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101115/"

["spice-0.12.5"]
cve = [ "CVE-2017-7506" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101098/"

["zlib-1.2.8"]
cve = [ "CVE-2016-9840", "CVE-2016-9842", "CVE-2016-9840", "CVE-2016-9842" ]
issue_url = "https://fb.flyingcircus.io/f/cases/27182/"

