["access"]
cve = [
    "CVE-2017-6399",
    "CVE-2017-6406",
    "CVE-2017-6400"
]
issue_url = "https://fb.flyingcircus.io/f/cases/28741/"
comment = "CVE applies only to Veritas NetBackup and NetBackup Appliance"

["bazaar-2.7.0"]
cve = [ "CVE-2017-14176" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101135/"

["bundler"]
cve = ["CVE-2016-7954"]
comment = "This is a usability issue that won't be fixed in bundler 1. The bundler developers declared this fixed for 1 by providing a blogpost: http://bundler.io/blog/2014/08/14/bundler-may-install-gems-from-a-different-source-than-expected-cve-2013-0334.html"

["curl-7.56.0"]
cve = [
    "CVE-2018-1000120",
    "CVE-2018-1000121",
    "CVE-2018-1000122",
    "CVE-2018-1000301"
]
issue_url = "https://fb.flyingcircus.io/f/cases/101151/"

["cyrus_sasl-2.1.26"]
cve = ["CVE-2013-4122"]
issue_url = "https://fb.flyingcircus.io/f/cases/26967/"
comment = "rejected"

["git"]
cve = [
    "CVE-2018-11233",
    "CVE-2018-11235"
]
issue_url = "https://fb.flyingcircus.io/f/cases/101837/"

["glibc-2.21"]
cve = [
    "CVE-2014-7817",
    "CVE-2014-8121",
    "CVE-2015-1781",
    "CVE-2015-7547",
    "CVE-2015-8983",
    "CVE-2015-8984",
    "CVE-2016-1234",
    "CVE-2016-3075",
    "CVE-2016-3706",
    "CVE-2017-16997",
]
issue_url = "https://fb.flyingcircus.io/f/cases/101913/"
comment = "CVE-2014-7817 fixed in 2.21 but CVE not updated"

["jasper-2.0.13"]
cve = ["CVE-2017-14229", "CVE-2017-14132"]
issue_url = "https://fb.flyingcircus.io/f/cases/101993/"

["libarchive-3.3.2"]
cve = [ "CVE-2017-14501",
        "CVE-2017-14503"
]
issue_url = "https://fb.flyingcircus.io/f/cases/100429/"

["libtiff-4.0.9"]
cve = [
    "CVE-2017-17095",
    "CVE-2017-17942",
    "CVE-2017-18013",
    "CVE-2018-5784",
    "CVE-2018-7456",
    "CVE-2018-8905",
    "CVE-2018-10126"]
issue_url = "https://fb.flyingcircus.io/f/cases/101123/"

["libvorbis-1.3.6"]
cve = [
    "CVE-2018-10393",
    "CVE-2018-10392"
]
issue_url = "https://fb.flyingcircus.io/f/cases/101912/"

["libx11-1.6.3"]
cve = [ "CVE-2016-7942", "CVE-2016-7943"]
issue_url = "https://fb.flyingcircus.io/f/cases/101153/"

["libxcursor-1.1.14"]
cve = [ "CVE-2017-16612" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101148/"

["libxpm-3.5.11"]
cve = [ "CVE-2016-10164"]
issue_url = "https://fb.flyingcircus.io/f/cases/101150/"

["libxrandr-1.5.0"]
cve = [ "CVE-2016-7947",
        "CVE-2016-7948"]
issue_url = "https://fb.flyingcircus.io/f/cases/101149/"

["libXrender-0.9.9"]
cve = [
    "CVE-2016-7950",
    "CVE-2016-7949"]
issue_url = "https://fb.flyingcircus.io/f/cases/101292/"

["libXv-1.0.10"]
cve = [ "CVE-2016-5407" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101279/"

["libXvMC-1.0.9"]
cve = [ "CVE-2016-7953" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101280/"

["openldap-2.4.45"]
cve = [
    "CVE-2017-17740",
    "CVE-2017-14159"
]
issue_url = "https://fb.flyingcircus.io/f/cases/101152/"

["openssl-1.0.2n"]
cve = [ "CVE-2018-0739", "CVE-2018-0737" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101281/"

["protobuf-2.6.1"]
cve = [ "CVE-2015-5237" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101115/"

["python-2.7.14"]
cve = "CVE-2018-1000030"
comment = "classified non-critical by Python devs"

["rsync-3.1.3"]
cve = [ "CVE-2017-16548" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101092/"

["shadow-4.5"]
cve = [ "CVE-2018-7169" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101090/"

["sharutils-4.15.2"]
cve = [ "CVE-2018-1000097" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101089/"

["spice-0.12.5"]
cve = [ "CVE-2017-7506" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101098/"

["vim-7.4.827"]
cve = [ "CVE-2017-17087"]
issue_url = "https://fb.flyingcircus.io/f/cases/101782/"

["w3m-0.5.3"]
cve= [
   "CVE-2018-6198",
   "CVE-2018-6196",
   "CVE-2018-6197"]
issue_url = "https://fb.flyingcircus.io/f/cases/100294/"

["zlib-1.2.8"]
cve = [ "CVE-2016-9840", "CVE-2016-9842", "CVE-2016-9840", "CVE-2016-9842" ]
issue_url = "https://fb.flyingcircus.io/f/cases/27182/"
