["bazaar-2.7.0"]
cve = [ "CVE-2017-14176" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101135/"

["curl-7.56.0"]
cve = [
    "CVE-2018-1000120",
    "CVE-2018-1000121",
    "CVE-2018-1000122"
]
issue_url = "https://fb.flyingcircus.io/f/cases/101151/"

["libtiff-4.0.9"]
cve = [ "CVE-2017-18013", "CVE-2017-17095", "CVE-2018-7456", "CVE-2018-8905", "CVE-2018-5784", "CVE-2017-17942" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101123/"

["libx11-1.6.3"]
cve = [ "CVE-2016-7942", "CVE-2016-7943"]
issue_url = "https://fb.flyingcircus.io/f/cases/101153/"

["libxcursor-1.1.14"]
cve = [ "CVE-2017-16612" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101148/"

["libxpm-3.5.11"]
cve = [ "CVE-2016-10164"]
issue_url = "https://fb.flyingcircus.io/f/cases/101150/"

["libxrandr-1.5.0"]
cve = [ "CVE-2016-7947",
        "CVE-2016-7948"]
issue_url = "https://fb.flyingcircus.io/f/cases/101149/"

["openldap-2.4.45"]
cve = [
    "CVE-2017-17740",
    "CVE-2017-14159"
]
issue_url = "https://fb.flyingcircus.io/f/cases/101152/"

["protobuf 2.6.1"]
cve = [ "CVE-2015-5237" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101115/"

["python-2.7.14"]
cve = "CVE-2018-1000030"
comment = "classified non-critical by Python devs"

["rsync-3.1.3"]
cve = [ "CVE-2017-16548" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101092/"

["spice-0.12.5"]
cve = [ "CVE-2017-7506" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101098/"

["w3m-0.5.3"]
cve= [
   "CVE-2018-6198",
   "CVE-2018-6196",
   "CVE-2018-6197"]
issue_url = "https://fb.flyingcircus.io/f/cases/100294/"

["zlib-1.2.8"]
cve = [ "CVE-2016-9840", "CVE-2016-9842", "CVE-2016-9840", "CVE-2016-9842" ]
issue_url = "https://fb.flyingcircus.io/f/cases/27182/"
