["access"]
cve = [
    "CVE-2017-6399",
    "CVE-2017-6406",
    "CVE-2017-6400"
]
issue_url = "https://fb.flyingcircus.io/f/cases/28741/"
comment = "CVE applies only to Veritas NetBackup and NetBackup Appliance"

["bundler"]
cve = ["CVE-2016-7954"]
comment = "This is a usability issue that won't be fixed in bundler 1. The bundler developers declared this fixed for 1 by providing a blogpost: http://bundler.io/blog/2014/08/14/bundler-may-install-gems-from-a-different-source-than-expected-cve-2013-0334.html"

["busybox-1.26.2"]
cve = ["CVE-2015-9261"]
issue_url = "https://fb.flyingcircus.io/f/cases/106543/"

["clamav-0.99.3"]
cve = [
    "CVE-2018-0202",
    "CVE-2018-1000085"
]
issue_url = "https://fb.flyingcircus.io/f/cases/101996/"

["coreutils-8.29"]
cve = ["CVE-2017-18018"]
issue_url = "https://fb.flyingcircus.io/f/cases/104708/"

["cyrus_sasl-2.1.26"]
cve = ["CVE-2013-4122"]
issue_url = "https://fb.flyingcircus.io/f/cases/26967/"
comment = "rejected"

["dovecot-2.1.17"]
cve = [
    "CVE-2017-15132",
    "CVE-2017-15130"]
issue_url = "https://fb.flyingcircus.io/f/cases/102039/"

["flac-1.3.2"]
cve = ["CVE-2017-6888"]
issue_url = "https://fb.flyingcircus.io/f/cases/103148/"

["git"]
cve = [
    "CVE-2018-11233",
    "CVE-2018-11235"
]
issue_url = "https://fb.flyingcircus.io/f/cases/101837/"

["glibc-2.21"]
cve = [
    "CVE-2014-7817",
    "CVE-2014-8121",
    "CVE-2015-1781",
    "CVE-2015-7547",
    "CVE-2015-8983",
    "CVE-2015-8984",
    "CVE-2016-1234",
    "CVE-2016-3075",
    "CVE-2016-3706",
    "CVE-2017-16997",
    "CVE-2017-18269"
]
issue_url = "https://fb.flyingcircus.io/f/cases/101913/"
comment = "CVE-2014-7817 fixed in 2.21 but CVE not updated"

["haproxy-1.5.14"]
cve = ["CVE-2018-10184"]
issue_url = "https://fb.flyingcircus.io/f/cases/103210/"

["jasper-2.0.13"]
cve = ["CVE-2017-14229", "CVE-2017-14132"]
issue_url = "https://fb.flyingcircus.io/f/cases/101993/"

["kibana-4.6.5"]
cve = ["CVE-2018-3819"]
issue_url = "https://fb.flyingcircus.io/f/cases/103301/"

["libarchive-3.3.2"]
cve = [ "CVE-2017-14501",
        "CVE-2017-14503"
]
issue_url = "https://fb.flyingcircus.io/f/cases/100429/"

["libgcrypt"]
cve = [ "CVE-2018-0495" ]
issue_url = "https://fb.flyingcircus.io/f/cases/105033/"

["libice-1.0.9"]
cve = [ "CVE-2017-2626" ]
issue_url = "https://fb.flyingcircus.io/f/cases/106544/"

["libsndfile-1.0.28"]
cve = [ "CVE-2018-13139",
        "CVE-2018-13419"]
issue_url = "https://fb.flyingcircus.io/f/cases/101041/"

["libtiff-4.0.9"]
cve = [
    "CVE-2017-11613",
    "CVE-2017-17095",
    "CVE-2017-18013",
    "CVE-2017-9935",
    "CVE-2018-10126",
    "CVE-2018-10963",
    "CVE-2018-5784",
    "CVE-2018-7456",
    "CVE-2018-8905",
]
comment = "Upstream version contains patches against these CVEs"
issue_url = "https://fb.flyingcircus.io/f/cases/101123/"

["libtiff"]
cve = ["CVE-2017-17942"]
until = "2018-08-24"
issue_url = "https://fb.flyingcircus.io/f/cases/104752/"

["libvorbis-1.3.6"]
cve = [
    "CVE-2018-10393",
    "CVE-2018-10392"
]
issue_url = "https://fb.flyingcircus.io/f/cases/101912/"

["libx11-1.6.3"]
cve = [ "CVE-2016-7942", "CVE-2016-7943"]
issue_url = "https://fb.flyingcircus.io/f/cases/101153/"

["libxcursor-1.1.14"]
cve = [ "CVE-2017-16612" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101148/"

["libxpm-3.5.11"]
cve = [ "CVE-2016-10164"]
issue_url = "https://fb.flyingcircus.io/f/cases/101150/"

["libxrandr-1.5.0"]
cve = [ "CVE-2016-7947",
        "CVE-2016-7948"]
issue_url = "https://fb.flyingcircus.io/f/cases/101149/"

["libXrender-0.9.9"]
cve = [
    "CVE-2016-7950",
    "CVE-2016-7949"]
issue_url = "https://fb.flyingcircus.io/f/cases/101292/"

["libXtst-1.2.2"]
cve = [
    "CVE-2016-7951",
    "CVE-2016-7952"]
issue_url = "https://fb.flyingcircus.io/f/cases/101997/"

["libXv-1.0.10"]
cve = [ "CVE-2016-5407" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101279/"

["libXvMC-1.0.9"]
cve = [ "CVE-2016-7953" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101280/"

["mariadb-10.0.32"]
cve = ["CVE-2017-15365"]
issue_url = "https://fb.flyingcircus.io/f/cases/104855/"

["mongodb-3.2.12"]
cve = ["CVE-2016-6494"]
issue_url = "https://fb.flyingcircus.io/f/cases/101998/"

["mysql-5.5.59"]
cve = [
    "CVE-2018-2781",
    "CVE-2018-2818",
    "CVE-2018-2817",
    "CVE-2018-2819",
    "CVE-2018-2755",
    "CVE-2018-2773",
    "CVE-2018-2761",
    "CVE-2018-2813",
    "CVE-2018-2771"
]
issue_url = "https://fb.flyingcircus.io/f/cases/102040/"

["nghttp2"]
cve = ["CVE-2018-1000168"]
issue_url = "https://fb.flyingcircus.io/f/cases/103149/"

["openjpeg-2.3.0"]
cve = [
    "CVE-2017-17479",
    "CVE-2017-17480",
    "CVE-2018-5727",
    "CVE-2018-5785",
    "CVE-2018-6616",
    "CVE-2018-7648"
]
issue_url = "https://fb.flyingcircus.io/f/cases/101999/"

["openldap-2.4.45"]
cve = [
    "CVE-2017-17740",
    "CVE-2017-14159"
]
issue_url = "https://fb.flyingcircus.io/f/cases/101152/"

["openssl-1.0.2n"]
cve = [ "CVE-2018-0739", "CVE-2018-0737" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101281/"

["openvpn-2.4.3"]
cve = [ "CVE-2017-12166" ]
issue_url = "https://fb.flyingcircus.io/f/cases/102038/"

["patch-2.7.6"]
cve = [
    "CVE-2018-1000156",
    "CVE-2018-6952",
    "CVE-2018-6951"
]
issue_url = "https://fb.flyingcircus.io/f/cases/104710/"

["postgres"]
cve = ["CVE-2018-1058"]
issue_url = "https://fb.flyingcircus.io/f/cases/104711/"

["postgres-9.6.7"]
cve = [ "CVE-2018-1058",
        "CVE-2018-1115"]
issue_url = "https://fb.flyingcircus.io/f/cases/104918/"

["protobuf-2.6.1"]
cve = [ "CVE-2015-5237" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101115/"

["python-2.7.14"]
cve = [ "CVE-2018-1060",
        "CVE-2018-1061" ]
issue_url = "https://fb.flyingcircus.io/f/cases/105034/"

["python"]
cve = "CVE-2018-1000030"
comment = "classified non-critical by Python devs"

["redis-3.0.2"]
cve = [ "CVE-2018-11218",
        "CVE-2018-11219",
        "CVE-2018-12453",
        "CVE-2016-10517"]
issue_url = "https://fb.flyingcircus.io/f/cases/105035/"

["rsync-3.1.3"]
cve = [ "CVE-2017-16548" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101092/"

["shadow-4.5"]
cve = [ "CVE-2018-7169" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101090/"

["sharutils-4.15.2"]
cve = [ "CVE-2018-1000097" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101089/"

["spice-0.12.5"]
cve = [ "CVE-2017-7506" ]
issue_url = "https://fb.flyingcircus.io/f/cases/101098/"

["systemd-237"]
cve = [ "CVE-2018-6954" ]
issue_url = "https://fb.flyingcircus.io/f/cases/105142/"

["vim-7.4.827"]
cve = [ "CVE-2017-17087"]
issue_url = "https://fb.flyingcircus.io/f/cases/101782/"

["w3m-0.5.3"]
cve= [
   "CVE-2018-6198",
   "CVE-2018-6196",
   "CVE-2018-6197"]
issue_url = "https://fb.flyingcircus.io/f/cases/100294/"

["zip-3.0"]
cve = [ "CVE-2018-13410" ]
issue_url = "https://fb.flyingcircus.io/f/cases/105205/"

["zlib-1.2.8"]
cve = [ "CVE-2016-9840", "CVE-2016-9842", "CVE-2016-9840", "CVE-2016-9842" ]
issue_url = "https://fb.flyingcircus.io/f/cases/27182/"

["zziplib-0.13.68"]
cve = [
    "CVE-2018-6869",
    "CVE-2018-7725",
    "CVE-2018-7726",
    "CVE-2018-7727"
]
issue_url = "https://fb.flyingcircus.io/f/cases/102000/"
